# Generated by Django 5.0 on 2023-12-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactivebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipbook',
            name='page_id',
            field=models.IntegerField(unique=True),
        ),
    ]
